### ISSUE TITLE
Будут замечания )

### ISSUE THREAD

**Issue by koras** [rationabilis/be12#1]

**Comment by koras** [comment]
Я посмотрел Ваш код, я думаю что Вам поможет вот эта ссылка [https://expressjs.com/ru/guide/routing.html](https://expressjs.com/ru/guide/routing.html)

К сожалению, я не смогу принять работу, пока вы не отладите скрипт.

Вот вам пример: я малясь подправил его, но я думаю вы догадаетесь как его использовать
const cardsRouter = require('express').Router();
const cards = require('../data/cards.json');

cardsRouter.use((req, res) => {
  res.send(cards);
});

module.exports = cardsRouter;

**Comment by koras** [comment]
Работу я принял, но без pull request тяжело их описывать. 
Сайт основной не работает, но задача не в этом, поэтому придираться не буду.
вместо "==" используйте "==="
В принципе всё

**Comment by koras** [comment]
Вопрос закрыт

**Comment by rationabilis** [comment]
Большое спасибо, Константин!
Думал, будет работать без выгрузки из Webpack и забыл про pull request.
Прошу прощения! 
Если вдруг еще будете проверять мои проекты, не принимайте работу в случае подобных косяков.
